// Noctigon KR4 by SammysHP
#include "cfg-noctigon-kr4.h"
// ATTINY: 1634

#undef RGB_LED_OFF_DEFAULT
#undef RGB_LED_LOCKOUT_DEFAULT
#undef RGB_RAINBOW_SPEED
#define RGB_LED_OFF_DEFAULT 0x14  // low, blue
#define RGB_LED_LOCKOUT_DEFAULT 0x10  // low, red
#define RGB_RAINBOW_SPEED 0x0f

#undef RAMP_SMOOTH_FLOOR
#undef RAMP_SMOOTH_CEIL
#undef RAMP_DISCRETE_FLOOR
#undef RAMP_DISCRETE_CEIL
#undef RAMP_DISCRETE_STEPS
#define RAMP_SMOOTH_FLOOR 3
#define RAMP_SMOOTH_CEIL 120
#define RAMP_DISCRETE_FLOOR 20
#define RAMP_DISCRETE_CEIL RAMP_SMOOTH_CEIL
#define RAMP_DISCRETE_STEPS 5

#define SIMPLE_UI_ACTIVE 0
