// Noctigon KR4 by SammysHP
#include "cfg-noctigon-kr4.h"
// ATTINY: 1634

#undef RGB_LED_OFF_DEFAULT
#undef RGB_LED_LOCKOUT_DEFAULT
#undef RGB_RAINBOW_SPEED
#define RGB_LED_OFF_DEFAULT 0x14  // low, blue
#define RGB_LED_LOCKOUT_DEFAULT 0x10  // low, red
#define RGB_RAINBOW_SPEED 0x0f

#undef RAMP_SMOOTH_FLOOR
#undef RAMP_SMOOTH_CEIL
#undef RAMP_DISCRETE_FLOOR
#undef RAMP_DISCRETE_CEIL
#undef RAMP_DISCRETE_STEPS
#define RAMP_SMOOTH_FLOOR 11
#define RAMP_SMOOTH_CEIL 120
#define RAMP_DISCRETE_FLOOR RAMP_SMOOTH_FLOOR
#define RAMP_DISCRETE_CEIL RAMP_SMOOTH_CEIL
#define RAMP_DISCRETE_STEPS 5

#undef BLINK_ONCE_TIME
#define BLINK_ONCE_TIME 32

#undef SIMPLE_UI_ACTIVE
#define SIMPLE_UI_ACTIVE 0

#undef DEFAULT_2C_STYLE
#define DEFAULT_2C_STYLE 2

#undef DEFAULT_DONT_RAMP_AFTER_MOON
#define DEFAULT_DONT_RAMP_AFTER_MOON 1

#undef AUTO_REVERSE_TIME
#define AUTO_REVERSE_TIME (TICKS_PER_SECOND / 2)
